### ISSUE TITLE
[Bolt 3.4] Block fields ordering breaks when re-ordering. 

### ISSUE THREAD

**Issue by bobdenotter** [BoltTranslate/Translate#157]
When you use the 'move down' and 'move up' buttons, the ordering of Blocks gets mixed up.. 

For example, this field def: 

```yml
        blockfoobar:
            type: block
            group: Blocks
            fields:
                foosection:
                    label: "Foo section"
                    fields:
                        heading:
                            type: text
                barsection:
                    label: "Bar section"
                    fields:
                        heading:
                            type: text
```

This happens in-browser: 

![](http://g.recordit.co/vFmdVlcItg.gif)

This only happens when Translate is installed.
