### ISSUE TITLE
[BUG] Fieldtype block translation always uses values from the bolt_field_value table

### ISSUE THREAD

**Issue by SanderOnline** [BoltTranslate/Translate#171]
I'm trying to use the Translate extension in combination with the fieldtype block but i'm having some issues to get it working and keep getting the same error.

Details
-------

 - Translate Version: [ 4.1.1 ]
 - Install type: [ Extension Repository ]
 - Bolt Version: [ 3.5.3 ]
 - PHP version: [ 5.6 ]

Reproduction
------------

I have a contenttype Pages with some dynamic nodes for the different contentblocks (getting the same errors if i don't use the nodes way):

```
pages:
    name: Paginas
    singular_name: Pagina
    fields:
        title:
            type: text
            label: Paginatitel
            class: large
            required: true
            translatable: true
            group: Eigenschappen            
        locale:
            type: locale            
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
            prefix: 'Introductietekst die getoond wordt onder de titel en bij de zoekresultaten'            
            translatable: true
        image:
            group: Header afbeelding
            type: image
            label: Header afbeelding
            upload: headers      
            prefix: 'Ideale formaat is 1920 pixels breed en 500 pixels hoog, andere formaten worden afgesneden om het passend te maken'
        contentblocks:
            type: block
            label: Content blokken
            group: Pagina content
            translatable: true
            fields:            
                <<: *textsection
                <<: *textsectionlayout
                <<: *videosection
                <<: *videosectionlayout
                <<: *bigimagesection
                <<: *bigimagetextsection
                <<: *blogsection
                <<: *quotesection
                <<: *reviewsection
                <<: *buttonssection               
        seo:
            type: seo
            group: "SEO instellingen"   
        template:
            type: templateselect 
        nldata:
            type: hidden
        nlslug:
            type: locale_data
            index: true
        dedata:
            type: hidden
        deslug:
            type: locale_data
            index: true                                              
    default_status: published
    recordsperpage: 30
    icon_many: "fa:file"
    icon_one: "fa:file"     
```

When i make a new page (standard in Dutch) and fill it with data the page shows and works. Now when i add a translation, in this case German, and save it, it always shows the Dutch translations for the block field values. All the other values like title, teaser etc work fine it only happens with the fields inside the block fieldtype.

When i look in the database the German block values are added to the record:

![record_data](https://user-images.githubusercontent.com/39906870/41418146-6e45ac88-6fef-11e8-9f9d-8f55191af450.jpg)

Then when looking in the bolt_field_value table the Dutch translation is there (i'm guessing this is how it is supposed to save the data):

![repeater_data](https://user-images.githubusercontent.com/39906870/41418305-bb8d36b4-6fef-11e8-8373-345348ca60fa.jpg)

When getting the data of the "textsection" I tried both following ways:
```
{{ item.content }}		
{{ item.get('content') }}
```
But both give the same result: the Dutch translation saved in the bolt_field_value  table.

Also, after i saved the German data in the adminpanel and switch back to Dutch nothing strange happens but when i then switch back to German i get the error message below and i'm stuck on this error even if i remove the translatable: true in my contentblocks node.

![page_error](https://user-images.githubusercontent.com/39906870/41418554-3a6acd20-6ff0-11e8-8878-1c8047a8072b.jpg)

Not sure if i did something wrong or fieldtype:block isn't supported at the moment. Hope the issue is clear, if you need more information just let me know.
