### ISSUE TITLE
[RFC] Add support for translatable contentblocks

### ISSUE THREAD

**Issue by blaues0cke** [BoltTranslate/Translate#172]
So it would be great to add support for translating contentblocks like:

```
pages:
    name: Seiten
    slug: seiten
    singular_slug: seite
    singular_name: Seite
    fields:
        title:
            type: text
            group: content
            label: Titel
        slug:
            type: slug
            uses: title
            label: Titel
        contentblocks:
            type: block
            label: Blöcke
            group: content
            fields:
                anchor_block:
                    label: Anker
                    fields:
                        anchor_id:
                            type: text
                            label: Anker-ID
```

It seems not to work right now since bolt will crash I add the extra fields (https://bolttranslate.github.io/Translate/example.html) to my `contenttypes.yml`.
