### ISSUE TITLE
[BUG] saving with templatefields throws: Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by zomars** [BoltTranslate/Translate#201]
Maybe I'm missing something here.

Details
-------

 - Translate Version: [ 4.1.6 ]
 - Install type: [ Extension Repository ]
 - Bolt Version: [ 3.6.4 ]
 - PHP version: [ 7.1 ]
 - Used webserver: [ Apache ] version [ 2.4 ]

Reproduction
------------

On `theme.yml`:
```yaml

templatefields:
    products.twig:
        foot_title:
            type: text
            translatable: true
        foot_subtitle:
            type: text
            translatable: true
        foot_content:
            type: html
            translatable: true
        foot_image:
            type: image
```

On my `contenttype.yml`:
```yaml 
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        subtitle:
            type: text
            class: large
        image:
            type: image
            placeholder: https://source.unsplash.com/1280x768/?business,workplace/__random__
        description:
            type: text
            class: large
            group: Explorer
        textlink:
            type: text
            label: "Text link"
        contentlink:
            type: text
            label: "Page link"
        template:
            type: templateselect
            filter: '*.twig'
        locale:
            type: locale
            group: content
        esdata:
            type: hidden
        esslug:
            type: locale_data
            index: true
        endata:
            type: hidden
        enslug:
            type: locale_data
            index: true
    recordsperpage: 4
    viewless: true
```
![image](https://user-images.githubusercontent.com/3504472/53209054-6be66900-35f6-11e9-943a-3a5c265a2fbb.png)

This is the full response: 
```json
{
    "success": false,
    "code": 500,
    "error": {
        "type": "\\ContextError",
        "file": "extensions\/vendor\/animal\/translate\/src\/EventListener\/StorageListener.php",
        "line": 269,
        "message": "Warning: Invalid argument supplied for foreach()"
    }
}
```
And full headers:
```
POST /bolt/editcontent/pages/1?_locale=en HTTP/1.1
Host: viva-organica-cms.localhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Referer: http://viva-organica-cms.localhost/bolt/editcontent/pages/1?_locale=en
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive
Cookie: bolt_session_3ae7df4b344d1122d8faa58950eb92c9=d75c6e69fafacbc41fcb61a354; bolt_authtoken_3ae7df4b344d1122d8faa58950eb92c9=ea0004108fd226dd89695a7cfac0f06389bee479f4fbfe63b58885dbbec0622d
cache-control: no-cache
Postman-Token: 89bd4cd6-2980-4b3a-acd6-985a17ced3f5
content_edit%5B_token%5D=--cYTRLwAVmok-sMgGC4MgR6kJdzTJGEKcXmGZo1a1E&editreferrer=&contenttype=pages&title=Best+flavored+products&slug=products&subtitle=All+our+work+is+focused+on+achieving+the+best+flavor.&image%5Bfile%5D=2019-01%2Fflavored-products.jpg&_locale=en&no_locale_hydrate=true&esdata=&endata=&description=All+our+work+is+focused+on+achieving+the+best+flavor.&textlink=View+products&contentlink=%2Fproducts&template=products.twig&templatefields%5Bfoot_title%5D=&templatefields%5Bfoot_subtitle%5D=&templatefields%5Bfoot_content%5D=&templatefields%5Bfoot_image%5D%5Bfile%5D=&id=1&status=published&datepublish=2019-01-28+15%3A51%3A55&datedepublish=&ownerid=1&_live-editor-preview=&content_edit%5Bsave%5D=undefined------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
