### ISSUE TITLE
[BUG] repeater field is set to a row prior when there's no translation being set on the current row

### ISSUE THREAD

**Issue by ridho-laksono-lamudi** [BoltTranslate/Translate#216]
Details
-------

 - Translate Version: [ master ]
 - Install type: [ all ]
 - Bolt Version: [ all ]
 - PHP version: [ all ]
 - Used webserver: [ all ]
 - For UX/UI issues: [ all ]

Reproduction
------------

1. set a translateable contenttypes in a repeater field
```
careers:
    name: Careers
    singular_name: Career
    fields:
        department:
            type: text
            class: large
            group: content
            required: true
            label: Department
            translatable: true
        position:
            type: repeater
            group: Job Vacancy
            label: Vacancy
            translatable: true
            initial: 0
            fields:
                title:
                    type: text
                    label: Job Title
                job_desc:
                    type: html
                    label: Job Description
```

2. contents example
```
row 1 english 
{
   department: "IT",
   position: [
     {
       title: "programmer",
       job_desc: "write code"      
     } 
   ]
}

row 1 deutsch
{
   department: "IT",
   position: [
     {
       title: "software entwickler",
       job_desc: "code schreiben"      
     } 
   ]
}

row 2 english
{
   department: "HR",
   position: [
     {
       title: "recruiter",
       job_desc: "recruits someone"      
     } 
   ]
}

row 2 deutsch
{
   department: "HR",
   position: <!-- DONT TRANSLATE -->
}
```

step 2:
create a multirow page to show all these data

current scenario: in Deutsch translation page on row 2, it will show "software entwickler"
expected scenario:in Deutsch translation page on row 2, it will show nothing
